---
- name: Configure GeoIP update
  template:
    src: 'GeoIP.conf.j2'
    dest: '{{ maxmind_update_configuration }}'
    owner: root
    group: root
    mode: 0640
  notify: Update GeoIP databases

- name: Install cron for automatic GeoIP database update
  template:
    src: 'geoipupdate.cron.j2'
    dest: '/etc/cron.d/geoipupdate'
    owner: root
    group: root
    mode: 0640
  notify: Restart cron